using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WorkOrderWizard.Models
{
    public class Employee
    {
        public Employee()
        {
            EmployeeFound = true;
        }

        public string emp_num { get; set; }
        public string name { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string mi { get; set; }

        public bool EmployeeFound { get; set; }
        public string OrigEmpNum { get; set; }
    }


    /*public partial class employee
    {
        public string emp_num { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string phone { get; set; }
        public string ssn { get; set; }
        public string dept { get; set; }
        public string emp_type { get; set; }
        public string pay_freq { get; set; }
        public Nullable<decimal> mfg_reg_rate { get; set; }
        public Nullable<decimal> mfg_ot_rate { get; set; }
        public Nullable<decimal> mfg_dt_rate { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string marital_stat { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public Nullable<System.DateTime> raise_date { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
        public string wc_class { get; set; }
        public Nullable<System.DateTime> term_date { get; set; }
        public string wage_acct { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<decimal> reg_rate { get; set; }
        public Nullable<decimal> ot_rate { get; set; }
        public Nullable<decimal> dt_rate { get; set; }
        public Nullable<byte> fwt_num { get; set; }
        public Nullable<decimal> fwt_dol { get; set; }
        public Nullable<byte> swt_num { get; set; }
        public Nullable<decimal> swt_dol { get; set; }
        public Nullable<byte> ost_num { get; set; }
        public Nullable<decimal> ost_dol { get; set; }
        public Nullable<byte> cwt_num { get; set; }
        public Nullable<decimal> cwt_dol { get; set; }
        public Nullable<decimal> state_cr { get; set; }
        public Nullable<byte> eic_cr { get; set; }
        public string state_code { get; set; }
        public string city_code { get; set; }
        public Nullable<byte> fica_exempt { get; set; }
        public Nullable<byte> fui_exempt { get; set; }
        public Nullable<byte> sui_exempt { get; set; }
        public string add_fwt_type { get; set; }
        public Nullable<decimal> add_fwt_amt { get; set; }
        public string add_swt_type { get; set; }
        public Nullable<decimal> add_swt_amt { get; set; }
        public string add_cwt_type { get; set; }
        public Nullable<decimal> add_cwt_amt { get; set; }
        public Nullable<decimal> vac_hr_due { get; set; }
        public Nullable<decimal> vac_hr_pd { get; set; }
        public Nullable<decimal> sick_hr_due { get; set; }
        public Nullable<byte> pension { get; set; }
        public Nullable<decimal> ins_prem { get; set; }
        public Nullable<byte> tip_cr { get; set; }
        public Nullable<decimal> union_amt { get; set; }
        public string union_type { get; set; }
        public string union_freq { get; set; }
        public string union_acct { get; set; }
        public Nullable<decimal> loan_amt { get; set; }
        public string loan_freq { get; set; }
        public Nullable<decimal> loan_bal { get; set; }
        public Nullable<decimal> garn_amt { get; set; }
        public string garn_type { get; set; }
        public string garn_freq { get; set; }
        public Nullable<decimal> garn_bal { get; set; }
        public string de_code__1 { get; set; }
        public string de_code__2 { get; set; }
        public string de_code__3 { get; set; }
        public string de_code__4 { get; set; }
        public string de_code__5 { get; set; }
        public string de_code__6 { get; set; }
        public string de_code__7 { get; set; }
        public string de_code__8 { get; set; }
        public string de_code__9 { get; set; }
        public string de_code__10 { get; set; }
        public string de_code__11 { get; set; }
        public string de_code__12 { get; set; }
        public string de_code__13 { get; set; }
        public string de_code__14 { get; set; }
        public string de_code__15 { get; set; }
        public Nullable<decimal> de_amt__1 { get; set; }
        public Nullable<decimal> de_amt__2 { get; set; }
        public Nullable<decimal> de_amt__3 { get; set; }
        public Nullable<decimal> de_amt__4 { get; set; }
        public Nullable<decimal> de_amt__5 { get; set; }
        public Nullable<decimal> de_amt__6 { get; set; }
        public Nullable<decimal> de_amt__7 { get; set; }
        public Nullable<decimal> de_amt__8 { get; set; }
        public Nullable<decimal> de_amt__9 { get; set; }
        public Nullable<decimal> de_amt__10 { get; set; }
        public Nullable<decimal> de_amt__11 { get; set; }
        public Nullable<decimal> de_amt__12 { get; set; }
        public Nullable<decimal> de_amt__13 { get; set; }
        public Nullable<decimal> de_amt__14 { get; set; }
        public Nullable<decimal> de_amt__15 { get; set; }
        public string de_freq__1 { get; set; }
        public string de_freq__2 { get; set; }
        public string de_freq__3 { get; set; }
        public string de_freq__4 { get; set; }
        public string de_freq__5 { get; set; }
        public string de_freq__6 { get; set; }
        public string de_freq__7 { get; set; }
        public string de_freq__8 { get; set; }
        public string de_freq__9 { get; set; }
        public string de_freq__10 { get; set; }
        public string de_freq__11 { get; set; }
        public string de_freq__12 { get; set; }
        public string de_freq__13 { get; set; }
        public string de_freq__14 { get; set; }
        public string de_freq__15 { get; set; }
        public Nullable<decimal> ytd_grs { get; set; }
        public Nullable<decimal> ytd_fwt_grs { get; set; }
        public Nullable<decimal> ytd_efica_gr { get; set; }
        public Nullable<decimal> ytd_rfica_gr { get; set; }
        public Nullable<decimal> ytd_fui_grs { get; set; }
        public Nullable<decimal> ytd_ost_grs { get; set; }
        public Nullable<decimal> ytd_wc_grs { get; set; }
        public Nullable<decimal> ytd_sb_grs { get; set; }
        public Nullable<decimal> ytd_sui_grs { get; set; }
        public Nullable<decimal> ytd_fica { get; set; }
        public Nullable<decimal> ytd_fwt { get; set; }
        public Nullable<decimal> ytd_eic { get; set; }
        public Nullable<decimal> ytd_swt { get; set; }
        public Nullable<decimal> ytd_ost { get; set; }
        public Nullable<decimal> ytd_cwt { get; set; }
        public Nullable<decimal> ytd_tip_cr { get; set; }
        public Nullable<decimal> de_bal__1 { get; set; }
        public Nullable<decimal> de_bal__2 { get; set; }
        public Nullable<decimal> de_bal__3 { get; set; }
        public Nullable<decimal> de_bal__4 { get; set; }
        public Nullable<decimal> de_bal__5 { get; set; }
        public Nullable<decimal> de_bal__6 { get; set; }
        public Nullable<decimal> de_bal__7 { get; set; }
        public Nullable<decimal> de_bal__8 { get; set; }
        public Nullable<decimal> de_bal__9 { get; set; }
        public Nullable<decimal> de_bal__10 { get; set; }
        public Nullable<decimal> de_bal__11 { get; set; }
        public Nullable<decimal> de_bal__12 { get; set; }
        public Nullable<decimal> de_bal__13 { get; set; }
        public Nullable<decimal> de_bal__14 { get; set; }
        public Nullable<decimal> de_bal__15 { get; set; }
        public string de_type__1 { get; set; }
        public string de_type__2 { get; set; }
        public string de_type__3 { get; set; }
        public string de_type__4 { get; set; }
        public string de_type__5 { get; set; }
        public string de_type__6 { get; set; }
        public string de_type__7 { get; set; }
        public string de_type__8 { get; set; }
        public string de_type__9 { get; set; }
        public string de_type__10 { get; set; }
        public string de_type__11 { get; set; }
        public string de_type__12 { get; set; }
        public string de_type__13 { get; set; }
        public string de_type__14 { get; set; }
        public string de_type__15 { get; set; }
        public string county { get; set; }
        public string country { get; set; }
        public Nullable<decimal> co_pd_ins { get; set; }
        public Nullable<decimal> empr_con { get; set; }
        public Nullable<decimal> ytd_co_pd_in { get; set; }
        public Nullable<decimal> ytd_empr_con { get; set; }
        public string shift { get; set; }
        public string pr_from { get; set; }
        public string charfld1 { get; set; }
        public string charfld2 { get; set; }
        public string charfld3 { get; set; }
        public Nullable<decimal> decifld1 { get; set; }
        public Nullable<decimal> decifld2 { get; set; }
        public Nullable<decimal> decifld3 { get; set; }
        public Nullable<byte> logifld { get; set; }
        public Nullable<System.DateTime> datefld { get; set; }
        public Nullable<byte> dir_dep { get; set; }
        public string ind_code { get; set; }
        public Nullable<byte> lunch_auto { get; set; }
        public string retire_type { get; set; }
        public Nullable<decimal> ytd_emp_con { get; set; }
        public Nullable<decimal> ytd_swt_grs { get; set; }
        public Nullable<decimal> ytd_cwt_grs { get; set; }
        public Nullable<decimal> ytd_med { get; set; }
        public Nullable<decimal> ytd_emed_grs { get; set; }
        public Nullable<decimal> ytd_rmed_grs { get; set; }
        public string addr__1 { get; set; }
        public string addr__2 { get; set; }
        public string addr__3 { get; set; }
        public string addr__4 { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public string mi { get; set; }
        public string bname { get; set; }
        public string nickname { get; set; }
        public string sex { get; set; }
        public Nullable<byte> no_chldrn { get; set; }
        public string spouse { get; set; }
        public string ph_ext { get; set; }
        public string ethnic_id { get; set; }
        public Nullable<byte> handicap { get; set; }
        public string military { get; set; }
        public string w_status { get; set; }
        public Nullable<byte> car_use { get; set; }
        public Nullable<byte> pct_use { get; set; }
        public Nullable<byte> car_allow { get; set; }
        public Nullable<decimal> ca_month { get; set; }
        public Nullable<decimal> camileage { get; set; }
        public Nullable<byte> citizen { get; set; }
        public string nationality { get; set; }
        public Nullable<System.DateTime> sb_date { get; set; }
        public Nullable<byte> no_dpndts { get; set; }
        public Nullable<System.DateTime> a_date { get; set; }
        public string app_num { get; set; }
        public Nullable<short> srv_leave { get; set; }
        public Nullable<short> srv_lyoff { get; set; }
        public string wage_acct_unit1 { get; set; }
        public string wage_acct_unit2 { get; set; }
        public string wage_acct_unit3 { get; set; }
        public string wage_acct_unit4 { get; set; }
        public string union_acct_unit1 { get; set; }
        public string union_acct_unit2 { get; set; }
        public string union_acct_unit3 { get; set; }
        public string union_acct_unit4 { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string work_country_code { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public string sname { get; set; }
        public byte[] picture { get; set; }
        public string email_addr { get; set; }
        public string business_phone { get; set; }
        public string uf_pref_type { get; set; }
    }*/
}