//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderWizard.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueryDefs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryDefs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkOrderWizard.Models.QueryDefs", typeof(QueryDefs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO WO
        ///(WONUM, CLOSEDATE, TASKDESC, WOTYPE, ORIGINATOR, PRIORITY, REQUESTTIME, REQUESTDATE )
        ///VALUES (&apos;~p0&apos;, &apos;~p1&apos;, &apos;~p2&apos;, &apos;~p3&apos;, &apos;~p4&apos;, ~p5, &apos;~p6&apos;, &apos;~p7&apos;).
        /// </summary>
        internal static string InsertIntoWO {
            get {
                return ResourceManager.GetString("InsertIntoWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO WOEQLIST
        ///(WONUM, CLOSEDATE, EQNUM,  LOCATION, SUBLOCATION1, SUBLOCATION2, SUBLOCATION3, DEPARTMENT, EQDESC)
        ///VALUES (&apos;~p0&apos;, &apos;~p1&apos;, &apos;~p2&apos;, &apos;~p3&apos;, &apos;~p4&apos;, &apos;~p5&apos;, &apos;~p6&apos;, &apos;~p7&apos;, &apos;~p8&apos;).
        /// </summary>
        internal static string InsertIntoWOEQLIST {
            get {
                return ResourceManager.GetString("InsertIntoWOEQLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM WO.
        /// </summary>
        internal static string SelectAllWorkOrders {
            get {
                return ResourceManager.GetString("SelectAllWorkOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 WONUM
        ///FROM WO
        ///WHERE WONUM LIKE &apos;~p0%&apos;
        ///ORDER BY WONUM DESC.
        /// </summary>
        internal static string SelectCurrentWONum {
            get {
                return ResourceManager.GetString("SelectCurrentWONum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM EQUIP
        ///WHERE INSERVICE = &apos;Y&apos;.
        /// </summary>
        internal static string SelectInServiceEquipment {
            get {
                return ResourceManager.GetString("SelectInServiceEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM employee
        ///WHERE emp_num = &apos;~p0&apos; and term_date IS NULL.
        /// </summary>
        internal static string SelectSLEmployeeByID {
            get {
                return ResourceManager.GetString("SelectSLEmployeeByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM WOEQLIST
        ///WHERE WONUM IN (~p0).
        /// </summary>
        internal static string SelectWOEQLISTByWONUMList {
            get {
                return ResourceManager.GetString("SelectWOEQLISTByWONUMList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM WOTYPE.
        /// </summary>
        internal static string SelectWOTypes {
            get {
                return ResourceManager.GetString("SelectWOTypes", resourceCulture);
            }
        }
    }
}
